### ISSUE TITLE
Extras 

### ISSUE THREAD

**Issue by Ashu3208** [divc13/Unified-Portal-For-Hall-Automation#15]
![image](https://user-images.githubusercontent.com/92543518/230590095-939e651c-5dff-40b5-a08b-7f20bf0f7b1b.png)
Extras are fixed for a particular meal.  But there is no option to set the option so that student can book the same extras on next meal.
Mess Manager have to  update the same extras on each repeated day, which basically becomes a manual labour and defeats the purpose of automation

**Comment by Kriti-Arora-08** [comment]
Since the prices of extras keep fluctuating, the mess manager would need to update them daily.
Updating extras daily also provides the system with the ability to adapt to any changes in the availability of items, for instance, if the mess is closed on some day due to pest control or there are more extras planned for a special occasion.
Hence if extras not updated daily, the system could not have managed that.

**Comment by Ashu3208** [comment]
No, the prices of a particular extra item is generally fixed.  Even if the price is changed, there should be option to update the price and when further onwards, if the same item is ordered, the updated price gets added in the bill .

**Comment by divc13** [comment]
It may not have come under your notice that prices of most extras change by some amount almost every one or 2 week. The point is for weekly extras, the mess manager only needs to add 7 more dates in the input. 

This daily updation system is justified in 2 ways:

1. confirmation every week: suppose due to some issues, some extras can not be made available, then in the weekly system, extras booking would have been automatically on, and the manager would have to manually change that. In case the manager forgets, it would cause havoc. **Updating extra items daily is a double check.**

2. If for some reasons, or for some special occasions, suppose the booking starts 15 days prior to the date of event. In this case, the start time and end time dates are must and week days would not help. **Updating extra items daily gives more flexilibility.**

Also this is according to our software requirements and should not be counted as an issue.
