### ISSUE TITLE
Mess menu-manager account

### ISSUE THREAD

**Issue by Ashu3208** [divc13/Unified-Portal-For-Hall-Automation#16]
![image](https://user-images.githubusercontent.com/92543518/230591318-808a07a1-5c8d-423c-a813-bb2e6cf75479.png)

Here in the 4th no, we haven't provided the item name and empty field cannot be submitted
But even if we didn't submit, a item with blank name shows on the mess page
![image](https://user-images.githubusercontent.com/92543518/230591515-7e3d048f-9d0b-4f8b-9847-6c112da20864.png)

**Comment by pranjalsingh4550** [comment]
This is a feature of the software: blank entries appear on the manager's interface but not the student's.
![image](https://user-images.githubusercontent.com/96577548/230743399-366f0043-151d-4a0d-ad2b-14bedee5849d.png)
This lets the manager to delete the item later or to continue editing.

**Comment by Ashu3208** [comment]
Blank entry only appears when you don't submit instead press back or navigate to different section.  If tis a feature, then blank submission should be allowed but should not appear on student's interface.
Also if blank submission is a feature, then multiple blank should also be allowed but it's not the case

**Comment by pranjalsingh4550** [comment]
(1) Yes, blank entries do not appear on the student's interface, as you said. This feature can be used if the manager accidentally clicks on modify menu, or while modifying menu, accidentally clicks on a different subsection/back/etc. But this is an exception and hence the Submit button is deactivated if any of the fields is blank, else the manager may click on it without having entered details of the addition/modification.
(2) Multiple blank entries need not be allowed - the above cases (accidentally clicking on modify menu or clicking on different subsection) can happen only once. You cannot make both mistakes at once, because either you did not intend to add something and accidentally clicked on "Modify", or you accidentally left the page while adding something. You are expected to correct the mistake if you make it, before repeating it.
(3) You complained about what you have asked for earlier, in issue #11. This is why we are not allowing multiple blank entries.
