### ISSUE TITLE
No option for hall manager to act on Cleaning request

### ISSUE THREAD

**Issue by Ashu3208** [divc13/Unified-Portal-For-Hall-Automation#26]
![image](https://user-images.githubusercontent.com/92543518/230676144-3a7808e5-6eee-441f-9c01-4d8318843bf7.png)
No option provided to approve request. Also hall manager don't have the option to validate that cleaning has been done. So if lot of students forget or don't click on done, unnecessary log of pending requests will be shown

**Comment by Sandeep-Nitharwal** [comment]
We have not provided any validation or approval request to the hall manager based on the current cleaning system, in which staff takes the sign of students after cleaning. So instead of signing student will validate the request on completion. 
And also If we provide these options to hall manager, he/she might use them in the wrong ways like not accepting requests or validating requests without cleaning work, etc.
I hope this help!

**Comment by Ashu3208** [comment]
People at managerials posts needs to be responsible and are generally while the same cannot be said for the student. 
There can be instances that even after cleaning of the room, student don't validate that and if a large number of students behave in this lazy manner, there will be lots of spam cleaning requests

**Comment by harshmohan21** [comment]
The cleaner is there to verify whether or not the student has validated their request. Currently, students do sign in the registers of the cleaners, so there is no reason to assume that students would behave in a lazy manner and not validate their request.
